CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku VARCHAR(64) NOT NULL,
  name VARCHAR(160) NOT NULL,
  description VARCHAR(500),
  category VARCHAR(100) NOT NULL,
  price NUMERIC(12, 2) NOT NULL,
  current_stock INTEGER NOT NULL DEFAULT 0,
  minimum_stock INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_products_sku UNIQUE (sku),
  CONSTRAINT chk_products_price CHECK (price >= 0),
  CONSTRAINT chk_products_current_stock CHECK (current_stock >= 0),
  CONSTRAINT chk_products_minimum_stock CHECK (minimum_stock >= 0),
  CONSTRAINT chk_products_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_products_category ON products (category);
CREATE INDEX idx_products_status ON products (status);
