CREATE TABLE inventory_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id VARCHAR(120),
  username VARCHAR(80) NOT NULL,
  display_name VARCHAR(140) NOT NULL,
  email VARCHAR(180),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_inventory_users_external_id UNIQUE (external_id),
  CONSTRAINT uk_inventory_users_username UNIQUE (username),
  CONSTRAINT uk_inventory_users_email UNIQUE (email),
  CONSTRAINT chk_inventory_users_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(80) NOT NULL,
  module VARCHAR(80) NOT NULL,
  description VARCHAR(255) NOT NULL,
  CONSTRAINT uk_permissions_code UNIQUE (code)
);

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(80) NOT NULL,
  name VARCHAR(120) NOT NULL,
  description VARCHAR(255),
  CONSTRAINT uk_roles_code UNIQUE (code)
);

CREATE TABLE role_permissions (
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
    REFERENCES roles (id) ON DELETE CASCADE,
  CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
    REFERENCES permissions (id) ON DELETE RESTRICT
);

CREATE TABLE user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
    REFERENCES inventory_users (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
    REFERENCES roles (id) ON DELETE RESTRICT
);

CREATE TABLE stock_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL,
  user_id BIGINT,
  movement_type VARCHAR(20) NOT NULL,
  previous_quantity INTEGER NOT NULL,
  new_quantity INTEGER NOT NULL,
  delta_quantity INTEGER NOT NULL,
  observations VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id)
    REFERENCES products (id) ON DELETE RESTRICT,
  CONSTRAINT fk_stock_movements_user FOREIGN KEY (user_id)
    REFERENCES inventory_users (id) ON DELETE SET NULL,
  CONSTRAINT chk_stock_movements_type CHECK (movement_type IN ('INITIAL', 'ENTRY', 'EXIT', 'ADJUSTMENT')),
  CONSTRAINT chk_stock_movements_previous_quantity CHECK (previous_quantity >= 0),
  CONSTRAINT chk_stock_movements_new_quantity CHECK (new_quantity >= 0)
);

CREATE INDEX idx_stock_movements_product_created_at
  ON stock_movements (product_id, created_at DESC);
