CREATE TABLE audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name VARCHAR(80) NOT NULL,
  record_id VARCHAR(80) NOT NULL,
  action VARCHAR(20) NOT NULL,
  actor_user_id BIGINT,
  old_values JSONB,
  new_values JSONB,
  correlation_id VARCHAR(100),
  event_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_audit_log_actor FOREIGN KEY (actor_user_id)
    REFERENCES inventory_users (id) ON DELETE SET NULL,
  CONSTRAINT chk_audit_log_action CHECK (action IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE INDEX idx_audit_log_table_record ON audit_log (table_name, record_id);
CREATE INDEX idx_audit_log_actor ON audit_log (actor_user_id);
