CREATE TABLE audit_revisions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision_timestamp BIGINT NOT NULL,
  username VARCHAR(120) NOT NULL
);

CREATE TABLE products_aud (
  id BIGINT NOT NULL,
  rev INTEGER NOT NULL,
  rev_type SMALLINT,
  sku VARCHAR(64),
  name VARCHAR(160),
  description VARCHAR(500),
  category VARCHAR(100),
  price NUMERIC(12, 2),
  current_stock INTEGER,
  minimum_stock INTEGER,
  status VARCHAR(20),
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  PRIMARY KEY (id, rev),
  CONSTRAINT fk_products_aud_revision FOREIGN KEY (rev)
    REFERENCES audit_revisions (id)
);

CREATE INDEX idx_products_aud_rev ON products_aud (rev);

CREATE TABLE stock_movements_aud (
  id BIGINT NOT NULL,
  rev INTEGER NOT NULL,
  rev_type SMALLINT,
  product_id BIGINT,
  user_id BIGINT,
  movement_type VARCHAR(20),
  previous_quantity INTEGER,
  new_quantity INTEGER,
  delta_quantity INTEGER,
  observations VARCHAR(500),
  created_at TIMESTAMPTZ,
  PRIMARY KEY (id, rev),
  CONSTRAINT fk_stock_movements_aud_revision FOREIGN KEY (rev)
    REFERENCES audit_revisions (id)
);

CREATE INDEX idx_stock_movements_aud_rev ON stock_movements_aud (rev);
CREATE INDEX idx_stock_movements_aud_product_rev ON stock_movements_aud (product_id, rev);
