{
 "title": "Inventory Final Observability",
 "tags": [
  "inventory",
  "observability"
 ],
 "panels": [
  {
   "title": "Infraestructura · Backend disponible",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"inventory-backend\"}"
    }
   ]
  },
  {
   "title": "Aplicación · Latencia P95",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"inventory-backend\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Negocio · Productos críticos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "inventory_products_critical" }
   ]
  },
  {
   "title": "Seguridad · Respuestas no autorizadas",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"inventory-backend\",status=~\"401|403\"}[5m]))"
    }
   ]
  },
  {
   "title": "Logs correlacionados",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{compose_service=\"backend\"}"
    }
   ]
  },
  {
   "title": "Trazas del backend",
   "type": "traces",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "{ resource.service.name = \"inventory-backend\" }"
    }
   ]
  }
 ]
}