spring.application.name=qa-gestion-inventarios

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventory}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:inventory_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cambiar}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_aud
spring.jpa.properties.org.hibernate.envers.revision_field_name=rev
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=rev_type
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
