# .github/workflows/conventional-commits.yml
name: Conventional Commits

on:
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  conventional-commits:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional Commits Action
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "feat,fix,test,chore,docs,ci,build,refactor,perf,security"