# .github/workflows/conventional-commits.yml
name: Conventional Commits

on:
  workflow_call:

permissions:
  contents: read

jobs:
  conventional-commits:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Conventional Commits Action
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "feat,fix,test,chore,docs,ci,build,refactor,perf,security"
